export enum StatusError {
  NOT_FOUND = 'NOT_FOUND',
  NOT_EXISTS = 'NOT_EXISTS',
  INVALID = 'INVALID',
  REPOSITORY_ERROR = 'REPOSITORY_ERROR',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
}
